In [1]:
import numpy as np
from numpy import array
from numpy import vstack,hstack

# 1. Create a 3x3x3 array with random values 

In [2]:
Z = np.random.uniform((3,3,3))
print (Z)

[2.04944161 2.82716314 1.39241553]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[9.65263295e-01 7.22206774e-01 2.83905378e-01 7.98900500e-01
  1.17989347e-01]
 [1.09733467e-01 2.70760700e-01 3.88293578e-02 8.91661873e-01
  8.59883690e-01]
 [1.24491938e-01 7.26003738e-01 6.23698024e-01 5.89539571e-01
  3.26402081e-01]
 [8.95549022e-01 5.03116445e-01 7.73021585e-04 5.00238082e-01
  0.00000000e+00]
 [5.62203388e-02 7.41650049e-01 1.01803804e-01 5.97042232e-01
  1.00000000e+00]]


# 5.  How to find common values between two arrays?

In [6]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-08-01
Today:  2020-08-02
Tomorrow:  2020-08-03


# 7. Consider two random array A and B, check if they are equal

In [8]:
x = np.random.randint(1,2,3)
print("First array:")
print(x)
y = np.random.randint(1,2,3)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 1 1]
Second array:
[1 1 1]
Test above two arrays are equal or not!
True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
A = np.random.random(10)
A[A.argmax()] = 0
print(A)

[0.18353738 0.57414615 0.         0.73492654 0.34619222 0.19799735
 0.55739687 0.16980497 0.52933832 0.34015151]


# 9. How to print all the values of an array?

In [10]:
my_array = np. arange(11)
print(my_array)
np. set_printoptions(threshold=np. inf)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


# 10.Subtract the mean of each row of a matrix

In [11]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[ 0.26549423,  0.36782931,  0.26954561, -0.07874553, -0.2831757 ,
        -0.25303355, -0.03099591,  0.31334769, -0.32138166, -0.24888449],
       [ 0.5684878 ,  0.05279328, -0.25487601, -0.25220355, -0.13438061,
         0.06764286, -0.05242374,  0.12942054,  0.01701352, -0.14147408],
       [-0.13370912, -0.09978065, -0.22771141,  0.46120901,  0.03495903,
         0.13633956,  0.05518192, -0.2156465 ,  0.3853606 , -0.39620243],
       [ 0.08517507,  0.30363478,  0.22275172,  0.21441937, -0.10185521,
         0.01117862, -0.20921568,  0.00304696, -0.52644239, -0.00269324],
       [-0.29578038, -0.27587999, -0.17256369,  0.12796873, -0.17535585,
         0.28235109,  0.03498508,  0.27463632,  0.5211385 , -0.32149979]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 4. 6. 2. 4. 1. 3. 2. 2. 2.]


# 12.How to get the diagonal of a dot product?

In [13]:
A = np.random.uniform(1,2,(3,3))
B = np.random.uniform(1,2,(3,3))
print(A)
print(B)
prod1=np.diag(np.dot(A, B))

[[1.03098118 1.11542083 1.59144252]
 [1.93731094 1.55092666 1.33707266]
 [1.90594654 1.62652971 1.64125109]]
[[1.03754652 1.56702327 1.01929386]
 [1.06049275 1.47497206 1.15995615]
 [1.80744119 1.64263935 1.36973246]]


# 13.How to find the most frequent value in an array?

In [14]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[7 6 8 6 5 8 6 0 3 7 4 7 3 9 1 1 6 1 0 6 2 9 2 5 1 5 1 0 2 6 9 8 5 8 0 1 3
 7 4 2]
Most frequent value in the above array:
1


# 14.How to get the n largest values of an array

In [15]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [16]:
A = np.array([("Hi", 2.5, 3),
              ("LetsUpgrade", 3.6, 2)])
B = np.core.records.fromarrays(Z.T)
print(B)

(4., 4., 6., 2., 4., 1., 3., 2., 2., 2.)
